version: '3'

services:
  db:
    image: postgres:11.2
    volumes:
      - ./api/local/initdb:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: chummy
    ports:
      - "5432:5432"
    expose:
      - "5432"
    command:
      - "postgres"
      - "-c"
      - "listen_addresses=*"
    restart: always
  redis:
    image: redis:latest
  api:
    image: notification-api
    restart: always
    build:
      context: api
      dockerfile: Dockerfile
      args:
        API_COMMIT: "${API_COMMIT}"
    environment:
      - REDIS_URL=redis://redis:6379/0
      - SQLALCHEMY_DATABASE_URI=postgresql://postgres:chummy@db:5432/notification_api
      - SQLALCHEMY_TEST_DATABASE_URI=postgresql://postgres:chummy@db:5432/test_notification_api
    entrypoint: /app/local/scripts/notify-web-entrypoint.sh
    command: make run
    volumes:
      - ./api/:/app
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
        - "6011:6011"
    depends_on:
      - db
      - redis
  admin:
    restart: on-failure
    image: notification-admin
    environment:
      - REDIS_URL=redis://redis:6379/0
    build:
      context: admin
      dockerfile: Dockerfile
      args:
        - ADMIN_COMMIT="${ADMIN_COMMIT}"
    command: make run-dev
    volumes:
      - ./admin/:/app
    ports:
        - "6012:6012"
  beat:
    image: notification-api
    restart: on-failure
    environment:
      - REDIS_URL=redis://redis:6379/0
      - SQLALCHEMY_DATABASE_URI=postgresql://postgres:chummy@db:5432/notification_api
    entrypoint: /app/local/scripts/notify-worker-entrypoint.sh
    command: >
      bash -c "sh scripts/run_celery_beat.sh"
    volumes:
      - ./api/:/app
    depends_on:
      - db
      - redis
      - api
  worker:
    image: notification-api
    restart: on-failure
    environment:
      - REDIS_URL=redis://redis:6379/0
      - SQLALCHEMY_DATABASE_URI=postgresql://postgres:chummy@db:5432/notification_api
    entrypoint: /app/local/scripts/notify-worker-entrypoint.sh
    command: >
      bash -c "[[ -f /tmp/celery.pid ]] && rm /tmp/celery.pid; sh /app/scripts/run_celery.sh"
    volumes:
      - ./api/:/app
    depends_on:
      - db
      - redis
      - api
  worker_sms:
    image: notification-api
    restart: on-failure
    environment:
      - REDIS_URL=redis://redis:6379/0
      - SQLALCHEMY_DATABASE_URI=postgresql://postgres:chummy@db:5432/notification_api
    entrypoint: /app/local/scripts/notify-worker-entrypoint.sh
    command: >
      bash -c "sh /app/scripts/run_celery_sms.sh"
    volumes:
      - ./api/:/app
    depends_on:
      - db
      - redis
      - api
