version: '3'

services:
  db:
    image: postgres:11.2
    volumes:
      - ./api/local/initdb:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: chummy
    ports:
      - "5432:5432"
    expose:
      - "5432"
    command:
      - "postgres"
      - "-c"
      - "listen_addresses=*"
    restart: always
  redis:
    image: redis:latest
  api:
    image: notification-api
    restart: always
    build:
      context: api
      dockerfile: Dockerfile
      args:
        API_COMMIT: "${API_COMMIT}"
    environment:
      - REDIS_URL=redis://redis:6379/0
      - SQLALCHEMY_DATABASE_URI=postgresql://postgres:chummy@db:5432/notification_api
      - SQLALCHEMY_TEST_DATABASE_URI=postgresql://postgres:chummy@db:5432/test_notification_api
    command: make run-dev
    volumes:
      - ./api/:/app
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
        - "6011:6011"
    depends_on:
      - db
      - redis
  admin:
    stdin_open: true
    tty: true
    restart: on-failure
    image: notification-admin
    environment:
      - REDIS_URL=redis://redis:6379/0
    build:
      context: admin
      dockerfile: Dockerfile
      args:
        - ADMIN_COMMIT="${ADMIN_COMMIT}"
    command: make run-dev
    volumes:
      - ./admin/:/app
      - ./utils/:/app/utils
    ports:
        - "6012:6012"
  beat:
    image: notification-api
    restart: on-failure
    environment:
      - REDIS_URL=redis://redis:6379/0
      - SQLALCHEMY_DATABASE_URI=postgresql://postgres:chummy@db:5432/notification_api
    command: make run-celery-beat
    volumes:
      - ./api/:/app
    depends_on:
      - db
      - redis
      - api
  worker:
    image: notification-api
    restart: on-failure
    environment:
      - REDIS_URL=redis://redis:6379/0
      - SQLALCHEMY_DATABASE_URI=postgresql://postgres:chummy@db:5432/notification_api
    command: make run-celery
    volumes:
      - ./api/:/app
    depends_on:
      - db
      - redis
      - api
